[package]
name = "skyway-webrtc-gateway-api"
version = "0.0.3"
authors = ["Toshiya Nakakura <nakakura@me.com>"]
edition = "2018"
license = "MIT"
description = "REST API Wrapper for SkyWay WebRTC Gateway"
repository = "https://github.com/nakakura/webrtc_gateway_controller"
readme = "README.md"
keywords = ["skyway", "webrtc", "gateway", "rtp"]
documentation = "https://docs.rs/skyway-webrtc-gateway-api"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
categories = ["api-bindings"]

[dependencies]
dotenv_codegen = "0.11.0"
env_logger = "0.6.2"
failure = "0.1.6"
futures = "0.3.1"
log = "0.4.8"
reqwest = { version = "0.10", features = ["json"] }
serde = { version = "1.0.104", features = ["derive"] }
serde_derive = "1.0.104"
serde_json = "1.0.44"
tokio = { version = "0.2.8", features = ["full"] }

[dev-dependencies]
async-std = "1.4.0"
either = "1.5"
http = "0.2"
httptest = "*"
hyper = { version = "0.13.1" }
mockito = "*"
toml = "0.5"
# internal crate for unit test of rest apis
helper = { path="./helper" }

[[example]]
name = "peer"
path = "example/peer.rs"

[[example]]
name = "data"
path = "example/data.rs"

[[example]]
name = "media"
path = "example/media.rs"
